# Generated by Django 2.0 on 2017-12-03 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20171203_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
